name: robinsr.github.io
description: Personal website of Ryan Robinson
url: https://ryanryan.net
google_verify: TODO

author:
    name: Ryan Robinson
    email: hi@ryanryan.net
    uri: https://ryanryan.net/about

permalink: /blog/post/:title

gems:
  - jekyll-sitemap

sass:
    style: compressed

collections:
  work:
    output: true
    permalink: /work/:name/

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .ruby-version
  - tailwind.config.js
  - postcss.config.js
  - assets/main.css
